### ISSUE TITLE
Https proxy not working

### ISSUE THREAD

**Issue by redyce** [go-resty/resty#200]
I've just tried resty with a https proxy, since its also available in Go since 1.10, but I got the following error both in client and request level:
`proxyconnect tcp: tls: oversized record received with length 20527`

**Comment by jeevatkm** [comment]
@redyce Thanks for reporting an issue.  Let me know have a look and get back.

**Comment by jeevatkm** [comment]
@redyce I did my analysis. I have grabbed HTTPS proxy server from this site https://www.sslproxies.org/ for testing, since I don't have any personal one.

I get the same error as you get in both resty and Go default HTTP client. I have `go1.11.1` in my machine.

Then I have tried the same proxy URL with `http` scheme it worked on both. Can you try at your end and please let me know? I don't have any lead here.

**Comment by jeevatkm** [comment]
@redyce Any updates?

**Comment by jeevatkm** [comment]
@redyce I'm closing this one. You could create a new issue with details. Thank you.
