### ISSUE TITLE
Cannot call SetRootCertificate with an oauth2 transport

### ISSUE THREAD

**Issue by asauber** [go-resty/resty#247]
Hi, I'd like to use an oauth2 client, as in the [this example.](https://github.com/go-resty/resty/issues/159#issuecomment-398240452)

However, when calling SetRootCertificate, we get this error:

```
RESTY 2019/06/11 17:59:30 ERROR current transport is not an *http.Transport instance
```

How can we make oauth2 clients compatible with `SetRootCertificate`?

**Comment by jeevatkm** [comment]
@asauber In the OAuth2 scenario, client supplied to Resty, so it uses the given client instead of creating one.  I believe OAuth2 library uses [http.RoundTripper](https://github.com/golang/oauth2/blob/master/transport.go#L27) based implementation. So you could possibly set root cert into the client before creating an OAuth2 instance.

**Comment by asauber** [comment]
I wasn’t able to modify properties of that RoundTripper, so I ended up using the the default client and adding the `Authorization: ` header manually. Works fine. Feel free to close.

**Comment by jeevatkm** [comment]
@asauber Thank you for the updates. I'm sorry to hear you're unable to use Resty for your use case. I will try to think of easy to use solution around it.
