### ISSUE TITLE
how to release memory?

### ISSUE THREAD

**Issue by rightjoin** [go-resty/resty#263]
Hi,

Thanks for creating this fantastic library. I was playing around with it and noticed a few things.

If I create a single client, my memory used for 25K requests is only 15MB (approx)

If I create 500 clients (and each client performs 50 requests), then I use 50MB approx.

If I create a new client per request (approx 25K clients and 1 req per client), then I use 125MB.

I tried other ways also (avoiding a single function stack), but saw same behaviour. My exploratory use case is price scraping, so would need a few hundred clients!

My question is: what is the best way to release memory used by a client? I didn't see any close method. 

`func getClient() *resty.Client {
	client := resty.New()
	client.SetRedirectPolicy(resty.FlexibleRedirectPolicy(10))
	return client
}

func fetchURL(client *resty.Client, url string) (*resty.Request, *resty.Response, error) {
	req := client.R()
	res, err := req.Get(url)
	return req, res, err
}

func fire(client *resty.Client, wg *sync.WaitGroup) {
	fetchURL(client, "http://abc.com/")
	wg.Done()
}

func takes15MB() {

	// single client instance
	client := getClient()

	for i := 1; i <= 500; i++ {
		var wg sync.WaitGroup
		for j := 1; j <= 50; j++ {
			wg.Add(1)
			go fire(client, &wg)
		}
		wg.Wait()
	}
}

func takes50MB() {

	for i := 1; i <= 500; i++ {
		// 500 clients
		client := getClient() 
		var wg sync.WaitGroup
		for j := 1; j <= 50; j++ {
			wg.Add(1)
			go fire(client, &wg)
		}
		wg.Wait()
	}
}

func takes125MB() {

	for i := 1; i <= 500; i++ {
		var wg sync.WaitGroup
		for j := 1; j <= 50; j++ {
			// 25000 clients
			client := getClient()
			wg.Add(1)
			go fire(client, &wg)
		}
		wg.Wait()
	}
}`

**Comment by jeevatkm** [comment]
@rightjoin Thank you for your appreciation. 

If you more resty client, I would suggest using no of clients based logic grouping. Technically there is no point creating more resty clients. Since resty has support fully qualified support for each request, you feel free to use one or fewer resty clients for your purpose.

In Go typically releasing memory is assigning `nil` to object then garbage collector will clean it from the heap.

what is the close method you're talking about? Resty already manages the internal HTTP client requests and response effectively.

**Comment by jeevatkm** [comment]
I'm closing this issue.
