### ISSUE TITLE
Is there a way to send a map[string]interface{} instead of map[string]string to SetQueryParams for resty?

### ISSUE THREAD

**Issue by ssmails** [go-resty/resty#265]
When using resty, sending query for GET using SetQueryParams(paramsMap) does not work. The same query when sent as part of the URL using Get(url) is ok.

"github.com/go-resty/resty"

client := resty.New()
resp, err := client.restyClient.R().
		SetHeader("Accept", "application/json").
		SetQueryParams(paramsMap).
		//Get(url)

DOES NOT WORK-
paramsMap before sending
INFO[0000] Params Map map[q:cicd.onboardStatus.code:$eq:2 q:table:$eq:CiCd] 

WORKS-
url = "https://api.dashboard-store.a.intuit.com/v1/raw/find/msok_state_prod?q:table:$eq=CiCd&q:cicd.onboardStatus.code:$eq:number=2"

Is there a way to send a map[string]interface{} instead of map[string]string to SetQueryParams for resty?
Suspecting the conversion to string is causing an issue.

**Comment by jeevatkm** [comment]
@ssmails Thanks for reaching out.

Following methods does not do any data type conversion, it only does compose query with values provided by you:
* https://godoc.org/github.com/go-resty/resty#Request.SetQueryParams
* https://godoc.org/github.com/go-resty/resty#Request.SetQueryParamsFromValues
* https://godoc.org/github.com/go-resty/resty#Request.SetQueryString

It is always good; the resty user performs the value conversion and provide string value to the resty library. So that resty doesn't have to figure out the data type conversion issues. That's why resty does not support `map[string]interface{}`.

**Comment by jeevatkm** [comment]
I'm closing this issue.
