### ISSUE TITLE
Make client.SetHeader() thread safe

### ISSUE THREAD

**Issue by amarjeetanandsingh** [go-resty/resty#383]
Hi

Is there any problem to make [client.SetHeader()](https://github.com/go-resty/resty/blob/9e4ce7a0b8e317309b9a8a3b4c7d4f058ac26a84/client.go#L164) thread safe? Any specific reason?

If performance impact is a reason, should we consider making it configurable or expose a safe api like `client.SetHeaderSafe()`?

@jeevatkm

**Comment by jeevatkm** [comment]
@amarjeetanandsingh Thanks for reaching out. Ideally, you create a Resty client once in the beginning, and requests made using that client across for the purpose.

Can you please share the scenario and your usage of the resty client? An example will help me to understand your usage.

**Comment by amarjeetanandsingh** [comment]
Thanks for your response @jeevatkm 

Agree that we should be creating resty client only once, but there can be a situation where we need to add one more request header later(_based on some condition_) to make this header available in every next request through this client. At that time we may run into race condition while setting up the new header.

If we don't want to update the header in resty client, another solution is to store the newHeader value somewhere in the global variable and add that in all the subsequent requests, which I feel wll be a lot more hassle. 

NOTE: Since resty client creation is a one time job, I feel making it thread safe wouldn't impact the performance.

**Comment by ben548** [comment]
i'm facing the same issue.
in my case, when i start a http request, i need to set authorization header for each requset.
i look deep down into the code, and realize the the SetHeader func is not thread safe, cause it use  map[string][]string as its datastruct, and i don't see any lock action.
so in my case, how can i make it thread safe? or i should just stop using resty and start finding some another go http request package in github?

**Comment by ben548** [comment]
I am facing a similar issue where I need to set an authorization header for each HTTP request I make. Upon examining the code, I realized that the SetHeader function is not thread-safe since it uses a map[string][]string as its data structure and I did not see any locking mechanism in place.

In this case, I am wondering how I can make it thread-safe or if I should consider using a different HTTP request package from GitHub.

**Comment by jeevatkm** [comment]
I'm considering using Mutex on the v3.0.0 at the client object level. Let's see the behavior afterward.

**Comment by amarjeetanandsingh** [comment]
@jeevatkm 
May I deliver this fix?

**Comment by SVilgelm** [comment]
@amarjeetanandsingh The PR you created fixes the only issue with writing the headers, but what will happen if another thread is reading those headers at same time?

In my opinion, there is no need in using the muteness to lock some particular resources in the client. It should be a global lock for any client properties. Also with the current code this will be very hard, since most of the properties are public.

In your case I would use a global mutex and use it everywhere in your application.

**Comment by amarjeetanandsingh** [comment]
Yes, @SVilgelm. The change needs a discussion to conclude.
IMO there is no straightforward way to make that thread-safe, the main reason being the exported variables.

However if we want to go ahead making it thread-safe, I feel we need to consider other APIs as well.

**Comment by jeevatkm** [comment]
@amarjeetanandsingh FYI, https://github.com/go-resty/resty/pull/717#issuecomment-1742211834

**Comment by zliang-akamai** [comment]
Would love to see this feature comes to reality 😍

**Comment by jeevatkm** [comment]
Resty v3 Client has a `sync.RWMutex` to make property modification concurrent-safe. Currently, the development version is available on the branch `main`.
