### ISSUE TITLE
PreMiddlewaresHook?

### ISSUE THREAD

**Issue by vacero** [go-resty/resty#440]
First of all, thanks for you awesome project!

I wanted to know if it would be possible to have a custom hook or a middleware that executes **before** any of the resty middlewares do. The context is that I am using the Path Parameters feature and I would like to access the raw string before the param values are applied by the resty middleware. I want to have metrics for each request with a path label, but I don't want a cardinality explosion by using the final URL path value, so using the path "template" would be ideal. 

Currently, I worked around this by setting a custom value in a context in `SetContext` but I would love to have a cleaner solution for this! Thanks!

**Comment by jeevatkm** [comment]
@vacero Thanks for reaching out and your appreciation.

I would like to clarify, you want to get this URL value `/v1/users/{userId}/{subAccountId}/details`, am I correct?

**Comment by vacero** [comment]
Sorry for the delay in the answer. Yes, that is correct, I want the string `/v1/users/{userId}/{subAccountId}/details` instead of the final one

**Comment by vacero** [comment]
@jeevatkm Any thoughts on this? Would it be possible to do?

**Comment by emilienkofman** [comment]
Hi and thanks for the great librarty!

I've been implementing prometheus latency histograms on resty calls using `SetPathParam` and since the histogram can only be computed in the response middlewares (and not in the request middlewares), I had the same issue, i.e. got a non-templated URL, and I'd like the templated URL for metrics accumulation. 

I've found no better way than passing it in context as @vacero suggests, maybe keeping untemplated URL in request attributes would make sense for such use case?
