### ISSUE TITLE
Is this project alive??

### ISSUE THREAD

**Issue by janekolszak** [go-resty/resty#611]
Hi!
I noticed there's not much going on with the project - Issues and PR's are piling.
Resty seems to be one of the more popular clients out there, it would be a waste if it just slowly ceased to work.

Are there any problems with maintenance, can I help?

**Comment by jeevatkm** [comment]
Hello @janekolszak - Resty project is alive. 

Due to a personal situation, I only spent a little time. If I remember correctly, my last work was migrating builds from Travis to GitHub actions.

I have been thinking lately about sorting out PRs for v2, parking a few for V3, and starting work on Resty v3.

----

Of course, helping hands are welcome, please feel free to review Issues and PRs. @moorereason is helping the Resty project.

**Comment by jeevatkm** [comment]
@janekolszak Thanks again! I'm closing it. Feel free to contribute to Resty.
