### ISSUE TITLE
Issues in using singleton resty 

### ISSUE THREAD

**Issue by chauhan17nitin** [go-resty/resty#612]
should i create singleton resty in my project, 
converted my simple resty to singleton and faced the issue, 

request going to completely different domain which is not specified in url

did anyone also faced the same?

**Comment by lordzsolt** [comment]
No. You should have 1 client per base URL (or domain)

**Comment by chauhan17nitin** [comment]
@lordzsolt any reasons for the above?

**Comment by segevda** [comment]
@chauhan17nitin Resty's client is not thread safe by design. What probably happens in your set up is a race between different goroutines. Imagine this flow:
```
A goroutine -> sets up a host address on the singleton client ("http://foo.com")
B goroutine -> sets up another host address on the singleton client ("http://bar.com")
A goroutine -> performs a request to "http://bar.com"
```

If you really want a singleton client, you should wrap it with a Mutex (or another locking pattern) to make sure the access to the client is sequential. But probably the better design here is to use separate clients.

**Comment by jeevatkm** [comment]
Thanks @lordzsolt and @segevda for your assistance.

@chauhan17nitin Typically, it is recommended to create a resty client instance per domain that you want to interact with.

If you really want to use single resty client instance then do not use SetBaseURL, instead always use absolute URL on the request.

**Comment by ground-beetle** [comment]
@jeevatkm thanks a lot for the answers! 😄 
Just to clarify: so, as long as `resty.Client` is used to query against the same domain (e.g. "google.com"), then single global instance of `resty.Client` can be used in parallel in different goroutines?
Thank you for the answer :)
