### ISSUE TITLE
Confusion between `set` and `add` methods

### ISSUE THREAD

**Issue by alexmontecucco** [go-resty/resty#67]
Hi,

I noticed an unexpected behavior for most of the `set` methods. This is from `request.go`:
```
func (r *Request) SetFormData(data map[string]string) *Request {
	for k, v := range data {
		r.FormData.Add(k, v)
	}
	return r
}
```
Most of the `set` methods are actually `add` which is misleading and prevents from overriding existing keys.
I don't know whether it is a design choice or not.

My suggestion would be to have both `set` and `add` methods (I have the changes locally). It would make things cleaner imo.

However, I am also aware that for functions such as  `SetQueryString` it might be possible to have multiple times the same key. 
It would be possible for the `set` functions to make them smarter and in case of multiple occurrences of one key, to first call `set` (which would erase the previously stored key) then call `add`.
Though I am not sure it would really be better.

Also, changing the current `set` methods to internally use a `set` call instead of an `add` call will break compatibility with code using the current behavior.

What is your opinion on the topic ?

**Comment by jeevatkm** [comment]
@alexmontecucco Sorry for delayed response. Just got occupied with my [aah framework](https://github.com/go-aah) work, getting ready to make an initial public release, etc.

When I designed the `resty`, I have followed convention of `golang` `Setter`.  You can see that with every method exposed from `resty` for setting values.

I understand your question, I hope and believe it won't hurt to change these two [`SetFormData`](https://github.com/go-resty/resty/blob/master/request.go#L135), [`SetQueryParam`](https://github.com/go-resty/resty/blob/master/request.go#L66) methods. Because `resty` already provides dedicated methods for setting multiple values `SetMultiValueQueryParams` and `SetMultiValueFormData`.

Now coming to your problem, as you have mentioned-

> prevents from overriding existing keys.

Can you please explain me your use case where you unable to do so?  The reason is if you're facing an issue other `resty` users could face. I would like to solve that. 

Looking forward to your response.

**Comment by alexmontecucco** [comment]
@jeevatkm Thx for you reply.
My concern is (from `request.go`):
```
// SetQueryParam method sets single paramater and its value in the current request.
// It will be formed as query string for the request.
// Example: `search=kitchen%20papers&size=large` in the URL after `?` mark.
// 		resty.R().
//			SetQueryParam("search", "kitchen papers").
//			SetQueryParam("size", "large")
// Also you can override query params value, which was set at client instance level
//
func (r *Request) SetQueryParam(param, value string) *Request {
	r.QueryParam.Add(param, value)
	return r
}
```
Both method name and doc are misleading because `SetQueryParam` is not setting but adding (`r.QueryParam.Add(param, value)`). 
`url.Values` type has four functions: `Get`, `Set`, `Add` and `Del`.
It is still possible to achieve the desired result by not using the `SetQueryParam` function and directly use the `QueryParam` attribute of the `Request` object though.

**Comment by jeevatkm** [comment]
Thanks @alexmontecucco. Okay let's make the misleading clear.

I will do this in coming `v0.12` release, I'm capturing it here so users can refer it -
 * `SetQueryParam ` and `SetFormData` will be updated to use method `Set` internally

`resty` user have to use existing methods `SetMultiValueQueryParams`, `SetMultiValueFormData` for multi values which uses method `Add` internally.

I hope this doesn't affect users.

_PS: If you're interested you can send PR for this update._

**Comment by alexmontecucco** [comment]
I don't understand why `SetMultiValueQueryParams` and `SetMultiValueFormData` still need to use  the `Add` internally. Is it to avoid breaking compatibility.

For `SetQueryParam` and `SetFormData` your suggestion is to simply change the `Add` to `Set` right ?

**Comment by jeevatkm** [comment]
No, it's not about breaking compatibility.

Yes, changing it from `Add` to `Set` for `SetQueryParam` and `SetFormData`.

---

The way `Set` works from `url.Values` is; it replaces the existing values. We will not able to add multi values. So `Add` is required for multi values.

Multi value method added on #28.

**Comment by alexmontecucco** [comment]
Ok got it, I forgot, thx.
Will push something this week / weekend.

**Comment by jeevatkm** [comment]
Thanks @alexmontecucco.

**Comment by alexmontecucco** [comment]
Closed by https://github.com/go-resty/resty/pull/71
