### ISSUE TITLE
Limit or provide a way to tackle Large payload size read on the Response body

### ISSUE THREAD

**Issue by youzeliang** [go-resty/resty#753]
In most cases, I use the resty library's Post method to send POST requests, and everything works fine with no issues. However, in a particular scenario, when I receive a large response structure, I encounter a memory leak. Firstly, I want to clarify that my code doesn't have any goroutine leaks or lingering global variables (i.e., no delayed releases). Upon using pprof to inspect, it seems that the underlying io.readAll operation is consuming a significant amount of memory. Are there considerations for optimizing this part? I will attach my pprof results and some key information along with the crucial parts of the code.

![profile001](https://github.com/go-resty/resty/assets/26573169/f87c8ddb-149e-45b8-b5f9-9f3efebdd1bb)

<img width="1050" alt="image" src="https://github.com/go-resty/resty/assets/26573169/0f29ae1b-9f18-4b12-b112-1ae0e8dee490">

`
	resty.New().
		OnBeforeRequest(func(client *resty.Client, r *resty.Request) error {
			return nil
		}).
		SetRetryCount(2).
		SetTimeout(time.Second * 8).
		R().
		SetFormData(apiBody).
		SetResult(&apiRes).
		Post(url)
`

the response apiRes is about 4k

**Comment by jeevatkm** [comment]
@youzeliang Thanks for reaching out. I'm currently on vacation days; I will be back in January.

**Comment by trungdlp-wolffun** [comment]
I see that code in resty/v2:

```go
func closeq(v interface{}) {
	if c, ok := v.(io.Closer); ok {
		silently(c.Close())
	}
}

func silently(_ ...interface{}) {}
```

**Comment by jeevatkm** [comment]
@youzeliang Thanks for reaching out. Based on the above details. Currently the method `R().SetFormData` reads all the form data values into memory to create Request body for the request. That's why memory increases. 

In the v3, there are plans to optimize the flow.

**Comment by jeevatkm** [comment]
Based on the issue details, I'm still determining whether 4k of response body size will cause a memory leak.

However, the issue raises a good point about utilizing streaming vs read-all.

In Resty v3 development, the request and response flow has been redesigned and optimized to add additional features. 

* It has exported the `Response.Body` [field](https://github.com/go-resty/resty/blob/9215e71cd392e74551ac99da29458ea5622f372f/response.go#L24)
* Response body limit reading [ability](https://github.com/go-resty/resty/blob/9215e71cd392e74551ac99da29458ea5622f372f/request.go#L684) 
* By default, using Decoder & Encoder to take advantage of streaming instead of Marshal and Unmarshal
* Reading response body [unlimited times](https://github.com/go-resty/resty/blob/9215e71cd392e74551ac99da29458ea5622f372f/request.go#L699)

Resty v3 brings many new features and improvements that enhance its functionality and performance.
