### ISSUE TITLE
Supporting  GET method with a request body is an option?

### ISSUE THREAD

**Issue by LiuZhiyan** [go-resty/resty#81]
Hello,

According to the logic at [0], the request body handling will be ignored for all the requests with GET method currently, however some servers are supporting this kind of API/request like Elasticsearch. I did some searches on this, HTTP/1.1 does not seem to explicitly forbid this (correct me if I miss anything), and it seems some people have the similar requirements as well. I consider this is kind of needs on unclear defined standard, but from the perspective of a generic RESTful client, do you think it's a cent we can get to open the limitation to allow downstream developer decides API design or usage, and resty supports that in anyway?

Thanks!

[0] https://github.com/go-resty/resty/blob/master/client.go#L855

**Comment by jeevatkm** [comment]
I understand your view point. There is a lot of discussions around this topic on SO [HTTP GET with body ](https://stackoverflow.com/questions/978061/http-get-with-request-body).

When I designed the `resty` I took approach of commonly followed. That's why I didn't added this support.

Elasticsearch does supports the POST request in parallel with GET request for the queries. 

I see only option/solution to this issue is -

> By default keep it disabled, provide an option to enable GET with payload. So developer can take the call.

Do you have any suggestion?

**Comment by LiuZhiyan** [comment]
Hello jeevatkm,

Thanks for your quick response.

Your design approach does make sense. I agree adding an option to do that seems like a good way to go currently, and disable the behavior by default to keep backward-compatible.

Would you like to take a look on my patch on this idea?

Thanks!

**Comment by jeevatkm** [comment]
Thank you for the PR, I have just added my review.
