### ISSUE TITLE
go-resty 2.14.0  import in golang 1.17.5 error

### ISSUE THREAD

**Issue by chy9003** [go-resty/resty#835]
my golang version is go 1.17.5 and import go-resty 2.14.0 ,but when run it report an error 

```
# golang.org/x/crypto/sha3
/Users/chy/go/pkg/mod/golang.org/x/crypto@v0.25.0/sha3/xor.go:25:3: undefined: subtle.XORBytes
note: module requires Go 1.20
# golang.org/x/net/http2
/Users/chy/go/pkg/mod/golang.org/x/net@v0.27.0/http2/transport.go:1078:13: tc.NetConn undefined (type *tls.Conn has no field or method NetConn)
note: module requires Go 1.18
```

so does go-resty 2.14.0 does not support go 1.17 ? 
ps: go mod file require go 1.16

**Comment by jeevatkm** [comment]
@chy9003 Thanks for reaching out. It seems I missed the go.mod go min version update to 1.18 when I refreshed the dependencies for `golang.org/x/net` and `golang.org/x/time` because the upstream net package had a CVE vulnerability.

I will correct the `go.mod`; I tested with `go1.19.13` before the v2.14.0 release.
